Repository gluonhq/scenebuilder, pull requests merged in 2021-09, with the labels that each got.

#399 Added checkstyle plugin to main POM.xml with basic config.
  .github/workflows/build.yml
  README.md
  checkstyle.xml
  pom.xml
Labels: housekeeping

#387 Fix for issue #386
  kit/src/main/java/com/oracle/javafx/scenebuilder/kit/library/user/LibraryFolderWatcher.java
Labels: bug, CLA signed

#410 release-drafter: categorize changes
  .github/release-drafter.yml
Labels: housekeeping

#380 Custom 'java.library.path' for Linux packages to avoid startup issues
  .github/workflows/linux.yml
  app/src/main/java/com/oracle/javafx/scenebuilder/app/about/AboutWindowController.java
  app/src/main/resources/com/oracle/javafx/scenebuilder/app/i18n/SceneBuilderApp.properties
Labels: bug

#409 Prepare SB 17
  .github/workflows/build.yml
  .github/workflows/kit.yml
  .github/workflows/linux.yml
  .github/workflows/mac.yml
  .github/workflows/win.yml
  app/pom.xml
  kit/pom.xml
  pom.xml
Labels: housekeeping

#407 Fix app name on Ubuntu
  .github/workflows/linux.yml
  app/assets/linux/SceneBuilder.desktop
Labels: bug

#415 Show Java version and runtime name in About Dialog
  app/pom.xml
  app/src/main/java/com/oracle/javafx/scenebuilder/app/about/AboutWindowController.java
Labels: enhancement, CLA signed
