Repository gluonhq/scenebuilder, pull requests merged in 2024-09, with the labels that each got.

#708 feat: Enabled loading of FXML files via drag&drop to WelcomeDialog. (…
  app/src/main/java/com/oracle/javafx/scenebuilder/app/welcomedialog/WelcomeDialogFilesDropHandler.java
  app/src/main/java/com/oracle/javafx/scenebuilder/app/welcomedialog/WelcomeDialogWindowController.java
  app/src/main/resources/com/oracle/javafx/scenebuilder/app/i18n/SceneBuilderApp.properties
  app/src/main/resources/com/oracle/javafx/scenebuilder/app/welcomedialog/WelcomeWindow.fxml
  app/src/test/java/com/oracle/javafx/scenebuilder/app/welcomedialog/WelcomeDialogFilesDropHandlerTest.java
Labels: enhancement

#724 build: incremented version number to snapshot of next major release
  app/pom.xml
  kit/pom.xml
  pom.xml
Labels: trivial, packaging

#732 fix: Constructor is now public (required for instantiation via FXML, issue 731).
  kit/src/main/java/com/oracle/javafx/scenebuilder/kit/util/control/paintpicker/PaintPickerController.java
Labels: bug

#730 feat: Remove deprecated API from JavaFX 23
  kit/src/main/java/com/oracle/javafx/scenebuilder/kit/util/CssInternal.java
Labels: housekeeping

#389 feat: ESC key selects parent of selected node
  kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/panel/content/ContentPanelController.java
  kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/panel/hierarchy/treeview/HierarchyTreeViewController.java
Labels: enhancement
